//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VWNewsclipApp.Models.EFModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VWModelsDBEntities : DbContext
    {
        public VWModelsDBEntities()
            : base("name=VWModelsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarModel> CarModels { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<SubModel> SubModels { get; set; }
        public virtual DbSet<SubModel_Feature> SubModel_Feature { get; set; }
    
        public virtual ObjectResult<JoinFeaturesModelsSubModels_Result> JoinFeaturesModelsSubModels()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<JoinFeaturesModelsSubModels_Result>("JoinFeaturesModelsSubModels");
        }
    
        public virtual int JoinModelFeatureSubModel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("JoinModelFeatureSubModel");
        }
    }
}
